import { z } from "zod";

export const reportSchema = z.object({
  id: z.string().uuid().optional(),
  title: z.string().min(1, "El título es obligatorio").max(255, "Máximo 255 caracteres"),
  slug: z.string().optional(), // auto-generated by backend
  summary: z.string().min(1, "El resumen es obligatorio"),
  citation_text: z.string().min(1, "El texto de citación es obligatorio"),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export const createReportSchema = reportSchema.omit({ id: true, slug: true });

export type ReportItem = z.infer<typeof reportSchema>;
export type CreateReportInput = z.infer<typeof createReportSchema>;
