from http import HTTPStatus


# API
API_PREFIX = "/api/v1"
API_VERSION = "1.0.0"
API_TITLE = "PhysaFlow API"

# Authentication
TOKEN_TYPE = "Bearer"
ADMIN_ROLE_NAME = "admin"

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100


# HTTP Status Codes
HTTP_200_OK = HTTPStatus.OK
HTTP_201_CREATED = HTTPStatus.CREATED
HTTP_204_NO_CONTENT = HTTPStatus.NO_CONTENT

HTTP_400_BAD_REQUEST = HTTPStatus.BAD_REQUEST
HTTP_401_UNAUTHORIZED = HTTPStatus.UNAUTHORIZED
HTTP_403_FORBIDDEN = HTTPStatus.FORBIDDEN
HTTP_404_NOT_FOUND = HTTPStatus.NOT_FOUND
HTTP_409_CONFLICT = HTTPStatus.CONFLICT
HTTP_422_UNPROCESSABLE_ENTITY = HTTPStatus.UNPROCESSABLE_ENTITY
HTTP_500_INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR