export interface TaxonomyConcept {
  id: string
  name: string
  shortDescription: string
  definition: string
  characteristics: string[]
  operationalImpact: string
  commonCauses: string[]
  exampleScenario: string
  relatedConceptIds: string[]
}

export interface TaxonomyCategory {
  id: string
  name: string
  description: string
  concepts: TaxonomyConcept[]
}

export const taxonomyData: TaxonomyCategory[] = [
  {
    id: "facility",
    name: "Facility",
    description: "Physical infrastructure constraints that limit data center compute capacity",
    concepts: [
      {
        id: "cooling-bottleneck",
        name: "Cooling Bottleneck",
        shortDescription:
          "Thermal constraints in data center cooling infrastructure that limit compute density and strand capacity.",
        definition:
          "A cooling bottleneck occurs when the facility's thermal management infrastructure cannot adequately dissipate heat generated by high-density compute deployments. This constraint forces operators to underutilize available power capacity to stay within thermal limits, effectively stranding otherwise usable compute resources. The bottleneck typically manifests at the CRAC unit, CRAH unit, or row-level cooling distribution level.",
        characteristics: [
          "Asymmetric heat distribution across server rows exceeding 4°C variance",
          "CRAC unit capacity utilization above 85% threshold",
          "Hot aisle containment failures due to bypass airflow",
          "Supply air temperature differential below 11°C design spec",
        ],
        operationalImpact:
          "Cooling bottlenecks reduce achievable rack density by 30–45%, forcing suboptimal server spacing and underutilized floor space. For a typical 5MW facility, this translates to 1.5–2.25MW of stranded capacity worth approximately $1.2–1.8M annually in lost revenue opportunity.",
        commonCauses: [
          "Oversubscribed CRAC units beyond nameplate capacity",
          "Blocked airflow pathways from underfloor cabling and debris",
          "Aging refrigerant loops with degraded heat exchange efficiency",
          "Inadequate hot aisle containment design or maintenance",
        ],
        exampleScenario:
          "A 40MW facility with 12 CRAC units rated at 350kW each should theoretically support 4.2MW of cooling. However, due to uneven airflow distribution and three units operating at 92% capacity while adjacent units idle at 40%, the effective cooling capacity drops to 3.1MW. The resulting 1.1MW gap represents stranded compute capacity that cannot be deployed despite available power and space.",
        relatedConceptIds: ["thermal-imbalance", "power-fragmentation"],
      },
      {
        id: "power-fragmentation",
        name: "Power Fragmentation",
        shortDescription:
          "Discontinuous power distribution that prevents full utilization of available electrical capacity across the data hall.",
        definition:
          "Power fragmentation describes the phenomenon where total facility power capacity exists but cannot be fully delivered to compute loads due to distribution topology constraints. Unlike a simple capacity shortfall, fragmentation creates isolated pockets of available power that cannot be aggregated, leaving operators unable to deploy dense compute configurations even when aggregate headroom appears sufficient.",
        characteristics: [
          "PDU capacity mismatches creating stranded pockets of 50–150kW each",
          "Phase imbalance exceeding 20% between distribution legs",
          "Breaker panel exhaustion at the row level despite overall headroom",
          "Transformer capacity segmentation limiting cross-row power sharing",
        ],
        operationalImpact:
          "Power fragmentation leaves 15–25% of contracted power stranded across typical deployments. A 10MW facility with 20% fragmentation effectively operates as an 8MW facility, representing $2–3M annually in stranded infrastructure investment. Remediation requires panel-level rebalancing or infrastructure upgrades.",
        commonCauses: [
          "Legacy power distribution designed for lower-density deployments",
          "Incremental capacity additions without holistic distribution planning",
          "Single-phase vs three-phase power mismatch at rack level",
          "Stranded whip cables and unused PDU breakers",
        ],
        exampleScenario:
          "A colocation data hall with 2MW total capacity distributes power across 16 PDUs. Three PDUs on the west row are at 95% capacity while five PDUs on the east row sit at 40%. Despite 320kW of total headroom, the west row cannot accept additional equipment, and the east row lacks the circuit capacity for dense GPU clusters due to breaker panel limitations.",
        relatedConceptIds: ["cooling-bottleneck", "storage-fragmentation"],
      },
      {
        id: "thermal-imbalance",
        name: "Thermal Imbalance",
        shortDescription:
          "Uneven temperature distribution across the data hall that forces overall cooling overprovisioning to compensate for localized hotspots.",
        definition:
          "Thermal imbalance refers to the non-uniform temperature profile across server rows, where localized hotspots force overall cooling system overprovisioning. The imbalance creates a paradox: the facility appears to have adequate cooling capacity, but hotspots at specific rack positions require lowering the entire room's supply temperature, wasting energy and limiting deployable density.",
        characteristics: [
          "Temperature variance exceeding 5°C across server rows",
          "Recirculation zones at row ends and above containment",
          "Inconsistent supply air distribution from perforated tile placement",
          "Return air temperature mixing losses above 15%",
        ],
        operationalImpact:
          "For every 1°C of overcooling required to compensate for hotspots, energy costs increase by 4–6%. Thermal imbalance typically forces 3–4°C of overcooling, wasting 12–24% of cooling energy. Beyond cost, the effective cooling capacity is reduced, stranding 10–15% of potential compute density.",
        commonCauses: [
          "Perforated tile misplacement or incorrect opening fractions",
          "Missing blanking panels creating bypass airflow paths",
          "Underfloor obstructions from cabling and piping",
          "Inconsistent CRAC unit setpoints across the facility",
        ],
        exampleScenario:
          "Thermal mapping of a 1000m² data hall reveals three hotspot zones at 28°C while the average supply temperature is 21°C. To protect equipment, the facility manager lowers the overall supply to 18°C, increasing cooling energy by 18%. Even then, two racks must remain underpopulated to avoid exceeding intake temperature thresholds, stranding 80kW of capacity.",
        relatedConceptIds: ["cooling-bottleneck", "idle-gpu-pool"],
      },
    ],
  },
  {
    id: "it",
    name: "IT",
    description: "Compute, network, and storage infrastructure inefficiencies that strand system-level capacity",
    concepts: [
      {
        id: "idle-gpu-pool",
        name: "Idle GPU Pool",
        shortDescription:
          "Allocated but underutilized GPU resources that consume power and cooling without delivering productive computation.",
        definition:
          "The idle GPU pool represents GPU instances that are provisioned and powered but executing minimal or no computational workloads. Unlike intentionally reserved capacity, these GPUs remain powered in an idle state—consuming 60–70% of peak power—while not contributing to job throughput. This is distinct from buffer capacity kept for elasticity, as idle pool GPUs have no pending workload assignment.",
        characteristics: [
          "GPU utilization below 5% sustained over 24-hour periods",
          "Memory allocated but compute engine idle for >80% of time",
          "Warm standby configuration without active failover purpose",
          "NVLink bridge utilization below 1% indicating no inter-GPU communication",
        ],
        operationalImpact:
          "Idle GPUs consume 60–70% of peak power while delivering zero useful output. A cluster of 32 idle A100 GPUs wastes approximately $180,000 annually in power and cooling alone. When amortized hardware costs are included, each idle GPU represents $8,000–12,000/year in stranded investment.",
        commonCauses: [
          "Overprovisioning for peak demand without dynamic scaling",
          "Lack of workload preemption for interactive jobs",
          "Reserved instances without utilization monitoring or automated release",
          "Fragmented GPU memory preventing consolidation of smaller jobs",
        ],
        exampleScenario:
          "An AI research cluster provisions 128 A100 GPUs across 16 nodes, with 40 GPUs reserved for peak training demand. User profiling reveals that peak utilization of the reserved pool occurs only 12 hours per week. The remaining 28 GPUs idle continuously, consuming 52kW of power and $140,000 annually in energy costs with zero productive output.",
        relatedConceptIds: ["queue-starvation", "resource-allocation"],
      },
      {
        id: "network-bottleneck",
        name: "Network Bottleneck",
        shortDescription:
          "Network fabric constraints that throttle inter-node communication and limit distributed workload performance.",
        definition:
          "Network bottlenecks occur when the switching fabric, link aggregation, or NIC configuration cannot sustain the bandwidth or latency demands of distributed computing workloads. In the context of stranded capacity, network bottlenecks prevent otherwise available compute resources from being effectively utilized, as jobs cannot scale efficiently across nodes.",
        characteristics: [
          "Port queue depth consistently exceeding 80% of buffer capacity",
          "TCP retransmission rate above 0.1% of total packets",
          "Ethernet pause frame flooding indicating congestion",
          "Inter-node latency variance (jitter) exceeding 10μs",
        ],
        operationalImpact:
          "Distributed training jobs experience 40–60% longer iteration times due to gradient synchronization waits. This effectively strands 30–50% of the compute investment, as GPUs sit idle waiting for network-delivered data. For a 256-GPU cluster, a 50% network-induced slowdown effectively wastes 128 GPUs' worth of compute time.",
        commonCauses: [
          "Oversubscribed top-of-rack switches beyond recommended ratios",
          "Insufficient spine bandwidth in leaf-spine topologies",
          "NIC offloading features disabled in driver configuration",
          "RoCE or InfiniBand congestion without adaptive routing",
        ],
        exampleScenario:
          "A distributed training job spans 64 nodes connected via 100Gbps Ethernet in a leaf-spine topology. During gradient all-reduce operations, the spine uplinks saturate at 95% utilization, causing collective communication time to dominate iteration time. Removing the network bottleneck via 200Gbps uplinks reduces training time from 72 hours to 43 hours, unlocking 40% more effective compute capacity without adding servers.",
        relatedConceptIds: ["storage-fragmentation", "resource-allocation"],
      },
      {
        id: "storage-fragmentation",
        name: "Storage Fragmentation",
        shortDescription:
          "Non-contiguous data allocation across parallel filesystems that degrades I/O performance and wastes storage capacity.",
        definition:
          "Storage fragmentation in parallel filesystems leads to data stripes distributed across non-optimal OSTs (Object Storage Targets) or OSDs (Object Storage Daemons), creating I/O hotspots and reducing effective throughput. The fragmentation increases latency for read/write operations and can cause significant capacity waste due to alignment padding and metadata overhead.",
        characteristics: [
          "OST utilization variance exceeding 20% across the filesystem",
          "File stripe width mismatch relative to application access patterns",
          "Metadata server latency spikes during directory listing operations",
          "Small-file overhead consuming >30% of total storage capacity",
        ],
        operationalImpact:
          "Checkpoint operations for large-scale simulations take 3x longer than with optimally allocated storage. I/O-bound jobs experience 25–40% longer runtime, effectively stranding the compute resources they occupy during extended I/O wait states. Storage capacity utilization efficiency drops to 60–70% due to fragmentation overhead.",
        commonCauses: [
          "Aggressive file creation without stripe width awareness",
          "Mixed workload I/O patterns (small random + large sequential)",
          "Inadequate filesystem rebalancing after hardware changes",
          "Suboptimal Lustre/GPFS stripe configuration defaults",
        ],
        exampleScenario:
          "A climate simulation writes 10TB checkpoint files to a Lustre filesystem with 24 OSTs. Due to default stripe configuration from initial deployment, all checkpoints stripe across only 4 OSTs, creating a 4× write bottleneck. After reconfiguring stripes to span all 24 OSTs, checkpoint time drops from 18 minutes to 4.5 minutes, recovering 75% of I/O-induced compute stall time across 512 simulation nodes.",
        relatedConceptIds: ["network-bottleneck", "resource-allocation"],
      },
    ],
  },
  {
    id: "workload",
    name: "Workload",
    description: "Job scheduling and resource management inefficiencies that strand allocation-level capacity",
    concepts: [
      {
        id: "queue-starvation",
        name: "Queue Starvation",
        shortDescription:
          "Jobs waiting indefinitely in scheduling queues due to priority inversion or resource hoarding by long-running workloads.",
        definition:
          "Queue starvation occurs when higher-priority or resource-intensive jobs perpetually block lower-priority workloads from acquiring necessary compute resources. Unlike simple resource contention, starvation is characterized by indefinite wait times where jobs never receive allocation despite available capacity elsewhere in the cluster, leading to systematic underutilization.",
        characteristics: [
          "Queue wait time exceeding 10× the job's estimated runtime",
          "Priority inversion cascades where low-priority jobs block medium-priority work",
          "Backlogged short-job queue despite available capacity on idle nodes",
          "Job walltime abandonment rates above 15% due to queue fatigue",
        ],
        operationalImpact:
          "20–35% of submitted jobs miss their SLA-defined completion windows due to queue contention. The resulting resource underutilization ranges from 15–25% of total cluster capacity, as jobs either wait indefinitely or users abandon submissions entirely. For a $10M cluster, this represents $1.5–2.5M in stranded investment annually.",
        commonCauses: [
          "First-come-first-serve queuing without backfill scheduling",
          "Overly conservative resource requests (4× actual utilization)",
          "Lack of preemption capability for batch workloads",
          "Insufficient queue partitioning for different workload classes",
        ],
        exampleScenario:
          "A research cluster using FCFS scheduling has 16 nodes reserved by four long-running jobs that each requested 4 nodes but consistently use only 2 nodes' worth of resources. The remaining 8 node-equivalents sit idle while 23 short jobs remain queued. Implementing backfill scheduling allows the short jobs to utilize idle resources, increasing effective throughput by 40% without adding hardware.",
        relatedConceptIds: ["scheduler-drift", "resource-allocation"],
      },
      {
        id: "scheduler-drift",
        name: "Scheduler Drift",
        shortDescription:
          "Progressive deviation between scheduler-allocated resources and actual workload utilization over time.",
        definition:
          "Scheduler drift is the phenomenon where the scheduler's resource allocation model diverges from actual workload resource consumption patterns, leading to increasingly inefficient placement decisions. This drift typically results from static scheduling policies that fail to account for evolving workload characteristics, hardware heterogeneity, or utilization feedback.",
        characteristics: [
          "Allocation-versus-utilization gap widening beyond 30%",
          "Stale node health data causing suboptimal placement",
          "Scheduler scoring model degradation over scheduling cycles",
          "Resource fragmentation increasing as drift compounds over time",
        ],
        operationalImpact:
          "Cluster utilization drops by 15–20% as the scheduler places jobs based on outdated resource models. The drift compounds over time, with each scheduling cycle reinforcing suboptimal placement patterns. For a 1,000-core cluster, scheduler drift effectively strands 150–200 cores that could be recovered through model recalibration.",
        commonCauses: [
          "Infrequent scheduler metric recalibration (quarterly or less)",
          "Static resource tags that don't reflect dynamic node conditions",
          "Node hardware heterogeneity not reflected in scheduler weightings",
          "Lack of automated feedback loops for scheduler parameter tuning",
        ],
        exampleScenario:
          "A Slurm-managed cluster was optimized for CPU-intensive MPI workloads six months ago. The workload has since shifted to GPU-accelerated ML training with different memory and network requirements. The scheduler continues to prioritize CPU-core count and memory locality, placing GPU jobs on suboptimal nodes and causing 25% longer runtimes. Recalibrating the scheduler weightings recovers 18% of effective cluster capacity.",
        relatedConceptIds: ["queue-starvation", "resource-allocation"],
      },
      {
        id: "resource-allocation",
        name: "Resource Allocation",
        shortDescription:
          "Suboptimal distribution of compute, memory, and I/O resources across competing workloads causing performance degradation.",
        definition:
          "Resource allocation inefficiency manifests when workloads receive disproportionate resource shares relative to their priority, requirements, or criticality. Unlike queue starvation (which prevents job start), allocation inefficiency affects running jobs through resource contention, oversubscription penalties, and non-optimal placement that degrades performance below what the hardware should deliver.",
        characteristics: [
          "CPU oversubscription exceeding 5:1 ratio causing throttling",
          "Memory ballooning without limits triggering swap thrashing",
          "NUMA node crossing penalties exceeding 20% performance loss",
          "Cache contention on shared LLC reducing per-core throughput",
        ],
        operationalImpact:
          "Mixed workloads on shared infrastructure experience 30–50% performance degradation due to resource contention. This effectively strands half the compute investment for affected workloads. In multi-tenant environments, allocation inefficiency can trigger noisy-neighbor scenarios where one tenant's performance collapses to 20% of baseline.",
        commonCauses: [
          "Lack of resource quotas or limits for workload classes",
          "Absence of quality-of-service tiers for mixed-criticality workloads",
          "Inadequate cgroup or container resource pinning",
          "Hypervisor resource scheduling overhead without mitigation",
        ],
        exampleScenario:
          "A Kubernetes cluster runs both latency-sensitive inference services and batch training jobs. Without QoS classes, a batch job spawning 200 pods consumes all available CPU cores, starving inference pods and increasing p99 latency from 15ms to 950ms. Implementing Guaranteed QoS for inference and Burstable for batch restores latency SLAs while allowing batch jobs to consume idle cycles.",
        relatedConceptIds: ["idle-gpu-pool", "scheduler-drift"],
      },
    ],
  },
]

export function getCategoryByConceptId(
  conceptId: string,
): TaxonomyCategory | undefined {
  return taxonomyData.find((cat) =>
    cat.concepts.some((c) => c.id === conceptId),
  )
}

export function getConceptById(
  conceptId: string,
): TaxonomyConcept | undefined {
  for (const cat of taxonomyData) {
    const concept = cat.concepts.find((c) => c.id === conceptId)
    if (concept) return concept
  }
  return undefined
}

export function getRelatedConcepts(
  conceptIds: string[],
): TaxonomyConcept[] {
  return conceptIds
    .map((id) => getConceptById(id))
    .filter((c): c is TaxonomyConcept => c !== undefined)
}

export function getAllConceptsFlattened(): TaxonomyConcept[] {
  return taxonomyData.flatMap((cat) => cat.concepts)
}

export function getAdjacentConcepts(
  conceptId: string,
): { prev: TaxonomyConcept | null; next: TaxonomyConcept | null } {
  const all = getAllConceptsFlattened()
  const index = all.findIndex((c) => c.id === conceptId)
  return {
    prev: index > 0 ? all[index - 1] : null,
    next: index < all.length - 1 ? all[index + 1] : null,
  }
}
