export interface TaxonomyConcept {
  id: string
  itemCode: string
  layerCode: string
  slug: string
  name: string
  shortDescription: string
  definition: string
  characteristics: string[]
  operationalImpact: string
  commonCauses: string[]
  exampleScenario: string
  relatedConceptIds: string[]
}

export interface TaxonomyCategory {
  id: string
  layerCode: string
  name: string
  description: string
  concepts: TaxonomyConcept[]
}

export const taxonomyData: TaxonomyCategory[] = [
  {
    id: "facility",
    layerCode: "FAC",
    name: "Facility",
    description: "Physical infrastructure constraints that limit data center compute capacity",
    concepts: [
      {
        id: "cooling-bottleneck",
        itemCode: "FAC-01",
        layerCode: "FAC",
        slug: "cooling-bottleneck",
        name: "Cooling Bottleneck",
        shortDescription:
          "Thermal constraints in data center cooling infrastructure that limit compute density and strand capacity.",
        definition:
          "A cooling bottleneck occurs when the facility's thermal management infrastructure cannot adequately dissipate heat generated by high-density compute deployments. This constraint forces operators to underutilize available power capacity to stay within thermal limits, effectively stranding otherwise usable compute resources. The bottleneck typically manifests at the CRAC unit, CRAH unit, or row-level cooling distribution level.",
        characteristics: [
          "Asymmetric heat distribution across server rows exceeding 4°C variance",
          "CRAC unit capacity utilization above 85% threshold",
          "Hot aisle containment failures due to bypass airflow",
          "Supply air temperature differential below 11°C design spec",
        ],
        operationalImpact:
          "Cooling bottlenecks reduce achievable rack density by 30–45%, forcing suboptimal server spacing and underutilized floor space. For a typical 5MW facility, this translates to 1.5–2.25MW of stranded capacity worth approximately $1.2–1.8M annually in lost revenue opportunity.",
        commonCauses: [
          "Oversubscribed CRAC units beyond nameplate capacity",
          "Blocked airflow pathways from underfloor cabling and debris",
          "Aging refrigerant loops with degraded heat exchange efficiency",
          "Inadequate hot aisle containment design or maintenance",
        ],
        exampleScenario:
          "A 40MW facility with 12 CRAC units rated at 350kW each could theoretically support 4.2MW of cooling. However, due to uneven airflow distribution and three units operating at 92% capacity while adjacent units idle at 40%, effective cooling drops to 3.1MW. The resulting 1.1MW gap represents stranded compute capacity that cannot be deployed despite available power and space.",
        relatedConceptIds: ["thermal-imbalance", "power-fragmentation"],
      },
      {
        id: "power-fragmentation",
        itemCode: "FAC-02",
        layerCode: "FAC",
        slug: "power-fragmentation",
        name: "Power Fragmentation",
        shortDescription:
          "Discontinuous power distribution that prevents full utilization of available electrical capacity across the data hall.",
        definition:
          "Power fragmentation describes a condition where total facility power capacity exists but cannot be fully delivered to compute loads due to distribution topology constraints. Unlike a simple capacity shortfall, fragmentation creates isolated pockets of available power that cannot be aggregated, leaving operators unable to deploy dense compute configurations even when aggregate headroom appears sufficient.",
        characteristics: [
          "PDU capacity mismatches creating stranded pockets of 50–150kW each",
          "Phase imbalance exceeding 20% between distribution legs",
          "Breaker panel exhaustion at the row level despite overall headroom",
          "Transformer capacity segmentation limiting cross-row power sharing",
        ],
        operationalImpact:
          "Power fragmentation strands 15–25% of contracted power across typical deployments. A 10MW facility with 20% fragmentation effectively operates as an 8MW facility, representing $2–3M annually in lost hosting opportunity. Remediation requires panel-level rebalancing or infrastructure upgrades.",
        commonCauses: [
          "Legacy power distribution designed for lower-density deployments",
          "Incremental capacity additions without holistic distribution planning",
          "Single-phase vs three-phase power mismatch at rack level",
          "Stranded whip cables and unused PDU breakers",
        ],
        exampleScenario:
          "A colocation data hall with 2MW total capacity distributes power across 16 PDUs. Three PDUs on the west row are at 95% capacity while five PDUs on the east row sit at 40%. Despite 320kW of total headroom, the west row cannot accept additional equipment, and the east row lacks the circuit capacity for dense GPU clusters due to breaker panel limitations.",
        relatedConceptIds: ["cooling-bottleneck", "storage-fragmentation"],
      },
      {
        id: "thermal-imbalance",
        itemCode: "FAC-03",
        layerCode: "FAC",
        slug: "thermal-imbalance",
        name: "Thermal Imbalance",
        shortDescription:
          "Uneven temperature distribution across the data hall that forces overall cooling overprovisioning to compensate for localized hotspots.",
        definition:
          "Thermal imbalance refers to the non-uniform temperature profile across server rows, where localized hotspots force overall cooling system overprovisioning. The imbalance creates a paradox: the facility appears to have adequate cooling capacity, but hotspots at specific rack positions require lowering the entire room's supply temperature, wasting energy and limiting deployable density.",
        characteristics: [
          "Temperature variance exceeding 5°C across server rows",
          "Recirculation zones at row ends and above containment",
          "Inconsistent supply air distribution from perforated tile placement",
          "Return air temperature mixing losses above 15%",
        ],
        operationalImpact:
          "For every 1°C of overcooling required to compensate for hotspots, energy costs increase by 4–6%. Thermal imbalance typically forces 3–4°C of overcooling, wasting 12–24% of cooling energy. Beyond cost, the effective cooling capacity is reduced, stranding 10–15% of potential compute density.",
        commonCauses: [
          "Perforated tile misplacement or incorrect opening fractions",
          "Missing blanking panels creating bypass airflow paths",
          "Underfloor obstructions from cabling and piping",
          "Inconsistent CRAC unit setpoints across the facility",
        ],
        exampleScenario:
          "Thermal mapping of a 1,000m² data hall reveals three hotspot zones at 28°C while the average supply temperature is 21°C. To protect equipment, the facility manager lowers the overall supply to 18°C, increasing cooling energy by 18%. Even then, two racks must remain underpopulated to avoid exceeding intake thresholds, stranding 80kW of capacity.",
        relatedConceptIds: ["cooling-bottleneck", "idle-gpu-pool"],
      },
      {
        id: "ups-efficiency",
        itemCode: "FAC-04",
        layerCode: "FAC",
        slug: "ups-efficiency",
        name: "UPS Efficiency Loss",
        shortDescription:
          "Power lost to heat and conversion inefficiency in UPS and PDU equipment that reduces deliverable compute capacity.",
        definition:
          "UPS efficiency loss captures the usable power that is dissipated as heat during conversion and conditioning across the uninterruptible power supply and distribution chain. Because capacity planning is performed against rated power, real conversion losses reduce the compute load that can actually be served, especially under light loading where efficiency drops sharply.",
        characteristics: [
          "UPS conversion efficiency falling below 92% at partial load",
          "Measured power factor degradation below managed load ratios",
          "PDU step-down transformer losses exceeding 3% of delivered power",
          "Idle battery float and inverter losses during normal operation",
        ],
        operationalImpact:
          "At partial loading a UPS can waste 5–12% of rated power as heat. On a 5MW facility operating at 70% load, conversion losses translate to roughly 175–420kW of unrecoverable capacity, costing $150,000–400,000 per year in utility spend while also raising CRAC demand.",
        commonCauses: [
          "Oversized UPS units running far below their ideal load band",
          "Legacy double-conversion topologies vs modern eco mode",
          "Overvoltage protection and filter hardware with high inrush overhead",
          "Incorrect power factor / sizing ratio, forcing linearity losses",
        ],
        exampleScenario:
          "A 2.5MW hall hosts 2MW of HPC load served by twin 1.25MW UPS modules. At night load drops to 1.1MW, placing each module at 44% load where efficiency falls to 88%. The 12% conversion loss wastes 132kW, costing $95,000 a year, and forces higher CRU setpoints that worsen thermal imbalance.",
        relatedConceptIds: ["power-fragmentation", "cooling-bottleneck"],
      },
      {
        id: "generator-transfer",
        itemCode: "FAC-05",
        layerCode: "FAC",
        slug: "generator-transfer",
        name: "Generator Transfer Risk",
        shortDescription:
          "Operational risk and downtime exposure when utility power loss requires transfer to backup generators during high-density loads.",
        definition:
          "Generator transfer risk arises when contingency power protection depends on automatic transfer to backup generation that may not fully sustain high-density compute loads. During a binding event the distribution chain can strand power, forcing operators to reserve capacity to stay within generator rating margin. The perceived risk reduces net deployable floor-and-power utilization even when no outage has occurred.",
        characteristics: [
          "Automatic transfer switch transition time above contractual RTO targets",
          "Generator rating margin below 10% of the planned peak high-density load",
          "Start and synchronization latencies exceeding 15 seconds",
          "Redundant generator health parameters falling out of readiness",
        ],
        operationalImpact:
          "Uncertain generator transfer forces operators to reserve 10–15% of hall capacity as standby headroom, stranding revenue on a 10MW hall. A conservative 5% additional reservation lowers net usable power by 500kW worth roughly $240,000 a year in missed revenue opportunity while heightening SLA-breach exposure.",
        commonCauses: [
          "Generator sizing below peak GPU aggregate draws",
          "ATS sequencing mismatched with UPS ramp rates",
          "Under-provisioned fuel volume or external capacity limits",
          "Lack of automated load-shedding programs to trim to generator capacity",
        ],
        exampleScenario:
          "A 12MW colocation hall hosts 10MW of GPU work. During a grid event the operator triggers generator transfer to a 2MW backup source. Because the upstream transfer sequence needs time to reach full output, the facility pulls 1.5MW of compute offline before transfer, stranding that workload for 3 hours and costing $6,000 in idle power.",
        relatedConceptIds: ["ups-efficiency", "power-fragmentation"],
      },
      {
        id: "space-underutilization",
        itemCode: "FAC-06",
        layerCode: "FAC",
        slug: "space-underutilization",
        name: "Space Underutilization",
        shortDescription:
          "Inefficient use of data hall floor space and raceway capacity that prevents dense rack packing and growth.",
        definition:
          "Space underutilization describes the degree to which deployable floor area and raceway volume are unavailable or wasted despite adequate power and cooling running. Because high-density racks often rely on specific positions near containment and raceway redundancy, static layout decisions can strand floor space that could otherwise host significant compute capacity.",
        characteristics: [
          "Active rack density below 60% of design intent in served rows",
          "Wasted raceway volume above 25% due to legacy containment",
          "Reserved floor span unused for growth for more than two quarters",
          "Cable tray volume occupied by oversized legacy trunks",
        ],
        operationalImpact:
          "Underutilized floor space on a 10,000m² hall with 30% unused raceway volume can prevent 15–25% of potential rack deployments, representing $3–6M in lost revenue opportunity. Reusing that capacity requires no new electrical or cooling build and comes at near-zero marginal cost.",
        commonCauses: [
          "Over-engineered raceway routing or overbuilt containment",
          "Legacy rack sizes and formats incompatible with modern GPU nodes",
          "Suboptimal placement of hot/cold aisle end caps",
          "No standards governing rack-to-rack spacing across tenants",
        ],
        exampleScenario:
          "A data center has 200 racks of 600mm width in a hall designed for 800mm GPU cabinets. Because existing power points and raceway align to legacy 600mm placement, only 120 of the 200 positions can host a dense GPU card. The other 80 positions accept only storage racks, leaving 40% of floor space unproductive for compute while the reserved power and cooling budget sits idle.",
        relatedConceptIds: ["power-fragmentation", "idle-gpu-pool"],
      },
      {
        id: "water-availability",
        itemCode: "FAC-07",
        layerCode: "FAC",
        slug: "water-availability",
        name: "Water Availability",
        shortDescription:
          "Insufficient access to cooling water that forces reduced chiller output or higher temperatures during dry periods.",
        definition:
          "Water availability covers the risk that cooling towers or chilled-water plants cannot source adequate process water during droughts, municipal allocation caps, or water quality degradation. Because compute density drives evaporative cooling, water scarcity forces operators to raise setpoints and shed load, stranding capacity precisely during peak demand.",
        characteristics: [
          "High-water conservation ratio falling below the required liters-per-kW threshold",
          "Chillers unable to hold target chilled supply temperatures on low water flow",
          "Cooling tower recirculation loss exceeding planned rates during dry months",
          "Water treatment cycles exceeding planned downtime requiring plain-water draw",
        ],
        operationalImpact:
          "Water-constrained sites can only serve 75–85% of their chilled-water-backed thermal capacity during dry season, stranding 1–2MW on a 5MW hall and adding $120,000–$300,000 of compensating dry-cooling and water import cost annually.",
        commonCauses: [
          "Municipal or utility water allocation caps enforced during drought",
          "Under-sized water storage volume for a high-density facility",
          "Evaporative cooling towers sized without seasonal capacity reserve",
          "Cooling load increasing faster than water make-up supply",
          "No alternative chip-level immersion or water reuse loops",
        ],
        exampleScenario:
          "A facility with a 4MW evaporative cooling plant forecasts a 6-week drought where municipal water allocation drops 40%. To protect operations, the operator raises chilled setpoints and caps GPU rows at 3.2MW, stranding 0.8MW during peak pricing weeks and spending $180,000 on trucked water make-up.",
        relatedConceptIds: ["cooling-bottleneck", "thermal-imbalance"],
      },
    ],
  },
  {
    id: "it",
    layerCode: "IT",
    name: "IT",
    description: "Compute, network, and storage infrastructure inefficiencies that strand system-level capacity",
    concepts: [
      {
        id: "idle-gpu-pool",
        itemCode: "IT-01",
        layerCode: "IT",
        slug: "idle-gpu-pool",
        name: "Idle GPU Pool",
        shortDescription:
          "Allocated but underutilized GPU resources that consume power and cooling without delivering productive computation.",
        definition:
          "The idle GPU pool represents GPU instances that are provisioned and powered but executing minimal or no computational workloads. Unlike intentionally reserved capacity, these GPUs remain powered in an idle state—consuming 60–70% of peak power—while not contributing to job throughput. This is distinct from buffer capacity kept for elasticity, and the pool often accumulates silently without monitoring.",
        characteristics: [
          "GPU utilization below 5% sustained over 24-hour periods",
          "Memory allocated but compute engine idle for >80% of time",
          "Warm standby configuration without active failover purpose",
          "NVLink bridge utilization below 3% indicating no inter-GPU communication",
        ],
        operationalImpact:
          "Idle GPUs consume 60–70% of peak power while delivering zero useful output. A cluster of 45 idle accelerators wastes roughly $180,000 annually in power and cooling alone. When amortized hardware cost is included, each idle GPU represents $8,000–12,000/year in stranded investment.",
        commonCauses: [
          "Overprovisioning for peak demand without dynamic scaling",
          "Lack of workload preemption for interactive jobs",
          "Reserved instances without utilization-monitoring or automatic release",
          "Fragmented memory preventing consolidation of smaller jobs",
        ],
        exampleScenario:
          "An AI research cluster provisions 128 A100 GPUs across 16 nodes, with 40 reserved for peak training demand. Profiling shows the reserved pool peaks only 12 hours per week. The remaining 28 GPUs idle continuously, consuming 52kW and $140,000 annually in energy with zero productive output.",
        relatedConceptIds: ["queue-starvation", "resource-allocation"],
      },
      {
        id: "network-bottleneck",
        itemCode: "IT-02",
        layerCode: "IT",
        slug: "network-bottleneck",
        name: "Network Bottleneck",
        shortDescription:
          "Network fabric constraints that throttle inter-node communication and limit distributed workload performance.",
        definition:
          "Network bottlenecks occur when the switching fabric, link aggregation, or NIC configuration cannot sustain the bandwidth or latency demands of distributed computing workloads. In the context of stranded capacity, network bottlenecks prevent otherwise available compute resources from being effectively used, as jobs cannot scale efficiently across nodes.",
        characteristics: [
          "Port queue depth consistently exceeding 80% of buffer capacity",
          "TCP retransmission rate above 0.1% of total packets",
          "Ethernet pause frame flooding indicating congestion",
          "Inter-node latency variance (jitter) exceeding 14μs",
        ],
        operationalImpact:
          "Distributed training jobs experience 40–60% longer iteration times due to gradient sync waits. This effectively strands 30–50% of the compute investment, as GPUs sit idle waiting for network delivery. For a 256-GPU cluster, a 50% slowdown wastes 128 GPUs of compute time.",
        commonCauses: [
          "Oversubscribed top-of-rack switches beyond recommended ratios",
          "Insufficient spine bandwidth in leaf-spine topologies",
          "NIC offloading features disabled in driver configuration",
          "RoCE or InfiniBand congestion without adaptive routing",
        ],
        exampleScenario:
          "A distributed training job spans 64 nodes on 100Gbps Ethernet in a leaf-spine topology. During gradient all-reduce, the spine uplinks saturate at 95%, making collective communication dominate iteration time. Moving to 200Gbps uplinks reduces runtime from 72 to 43 hours, unlocking 40% more effective compute without adding devices.",
        relatedConceptIds: ["storage-fragmentation", "resource-allocation"],
      },
      {
        id: "storage-fragmentation",
        itemCode: "IT-03",
        layerCode: "IT",
        slug: "storage-fragmentation",
        name: "Storage Fragmentation",
        shortDescription:
          "Non-contiguous data allocation across parallel filesystems that degrades I/O performance and wastes storage capacity.",
        definition:
          "Storage fragmentation in parallel filesystems leads to data stripes distributed across non-optimal OSTs (Object Storage Targets) or OSDs (Object Storage Daemons), creating I/O hotspots and reducing effective throughput. The extra latency increases I/O-bound job runtime and can cause significant capacity waste from alignment padding and metadata overhead.",
        characteristics: [
          "OST utilization variance exceeding 20% across the filesystem",
          "File stripe count mismatch vs application access patterns",
          "Metadata server latency spikes during directory listing",
          "Small-file overhead consuming >30% of total storage capacity",
        ],
        operationalImpact:
          "Checkpoint operations take 3x longer than with optimally stored files. I/O-bound jobs experience 25–40% longer runtime, stranding the compute they occupy during extended wait. Storage capacity efficiency drops to 60–70% due to fragmentation overhead.",
        commonCauses: [
          "Aggressive file creation without stripe-width awareness",
          "Mixed workload I/O (small random + large sequential) on one system",
          "Inadequate filesystem rebalancing after hardware changes",
          "Suboptimal Lustre/GPFS stripe configuration defaults",
        ],
        exampleScenario:
          "A climate simulation writes 10TB checkpoints to a Lustre filesystem with 24 OSTs. Default striping sends all checkpoints to only 4 OSTs, creating a 4x write bottleneck. Reconfiguring stripes to span all 24 OSTs drops checkpoint time from 18 to 4.5 minutes, recovering 75% of I/O-induced stall across 512 simulation nodes.",
        relatedConceptIds: ["network-bottleneck", "resource-allocation"],
      },
      {
        id: "memory-bottleneck",
        itemCode: "IT-04",
        layerCode: "IT",
        slug: "memory-bottleneck",
        name: "Memory Bottleneck",
        shortDescription:
          "HBM and system DRAM pressure that limits how much of each accelerator's raw compute can be exercised per workload.",
        definition:
          "A memory bottleneck describes how on-die HBM bandwidth and capacity, or scarce system DRAM, is insufficient to feed the compute engines, so kernels spend a large fraction of time waiting on memory. In dense ML training the effective FLOPS per GPU falls far below spec because data cannot move fast enough.",
        characteristics: [
          "HBM bandwidth utilization above 85% during compute phases",
          "DRAM spilling or swapping to SSD when working sets exceed sockets",
          "GPU tensor core occupancy below 50% in memory-bound layers",
          "Page or allocation throttling for large batched KV caches",
        ],
        operationalImpact:
          "Memory-bound training runs achieve 30–55% of theoretical FLOPS. A 256-GPU cluster running at half of theoretical capability wastes 128 accelerators of paid capacity; rebalancing onto richer HBM tiers can recover 25–40% of throughput without additional silicon.",
        commonCauses: [
          "HBM sized below large parameter or KV-cache capacity",
          "Imbalanced memory rows causing one node to block distributed jobs",
          "No HBM tiering or processor allocation based on memory footprint",
          "Lack of in-memory data staging and caching for hot workloads",
        ],
        exampleScenario:
          "An inference farm of 128 H200s runs a 175B LLM. During K/V-bound generation the model hits the HBM limit, and 60% of request time is spent memory-limited. Switching to fused-precision sampling and tighter KV compaction lifts effective throughput from 55% to 82% of spec, recovering 27% of fleet capacity without adding cards.",
        relatedConceptIds: ["idle-gpu-pool", "pcie-saturation"],
      },
      {
        id: "pcie-saturation",
        itemCode: "IT-05",
        layerCode: "IT",
        slug: "pcie-saturation",
        name: "PCIe Saturation",
        shortDescription:
          "PCIe bus and I/O throughput ceiling that caps accelerator-to-host and storage data movement.",
        definition:
          "PCIe saturation occurs when the Peripheral Component Interconnect Express bus between accelerators, host memory, and network devices becomes the bottleneck for data movement. Even when accelerators and storage are individually sufficient, a saturated bus throttles aggregated compute, so larger jobs scale minimally.",
        characteristics: [
          "PCIe link utilization above 85% during mixed I/O",
          "NVMe-storage traffic crossing PCIe exceeding host allocation",
          "DMA transactions stalling during high data-plane bursts",
          "Accelerators data-starved during high transfer windows on the bus",
        ],
        operationalImpact:
          "PCIe saturation cuts sustained I/O-to-accelerator throughput 20–40%, lengthening workloads by 25–50%. For a 16-node cluster this represents a meaningful $500k/yr in lost compute opportunity, equivalent to the value of 22 additional accelerator cards.",
        commonCauses: [
          "Incorrect lane assignment for accelerator cards",
          "Gen4 cards seated in Gen3 slots, dropping link speed",
          "Storage-array drivers using inefficient PCIe polling modes",
          "Mixed workloads oversubscribing shared host lanes",
        ],
        exampleScenario:
          "A server with 8x 3.2TB NVMe and 4x A100 accelerators serves a rendering farm. Concurrent storage reads saturate the shared PCIe bus far below the NVMe parallel capability. Reallocating storage cards to dedicated IOMMU lanes and increasing queue depth removes the wait, shrinking the rendering window by 19%.",
        relatedConceptIds: ["network-bottleneck", "memory-bottleneck"],
      },
      {
        id: "power-capping",
        itemCode: "IT-06",
        layerCode: "IT",
        slug: "power-capping",
        name: "Accelerator Power Capping",
        shortDescription:
          "Firmware-enforced power limits on accelerators that throttle compute to prevent oversubscription but strand rated performance.",
        definition:
          "Accelerator power capping is the intentional or insurance-enforced limit on heat draw per GPU or per node. When operators cap power to avoid grid trips or cooling peaks, the accelerators run below their continuous windows, so theoretical FLOPS are never reached—safe behavior that strands rated capability.",
        characteristics: [
          "Long-duration jobs running at lower than in-band core frequency",
          "Consistent measured card draw peaking at the TDP cap",
          "Cluster-wide power budget managed to a platform limit",
          "Boost clock abandoned during elevated temperature windows",
        ],
        operationalImpact:
          "Power capping at 75–90% of allowance reduces sustained performance 10–25% while providing 8–15% power relief. A 1MW GPU load capped at 87% yields roughly 130kW of power headroom yet slower batch completions; the dollar trade-off is stranded compute plus SLA risk.",
        commonCauses: [
          "Facility-imposed caps to brace for grid constraints",
          "Chiller or PDU-level limits trimming power ahead of cooling capacity",
          "Legacy firmware capping tables left from seasonal adjustments",
          "Insufficient allowance for burst amperage",
        ],
        exampleScenario:
          "A provider caps 1,024 GPUs to 80% TDP after a power board issue. Batch training that should complete in 12h now takes 14.8h, consuming less power but stretching timelines 23%. Recapturing the 2.8h of lost throughput effectively strands 40% of the accelerator spend for the duration of the training run.",
        relatedConceptIds: ["idle-gpu-pool", "network-bottleneck"],
      },
    ],
  },
  {
    id: "workload",
    layerCode: "WKL",
    name: "Workload",
    description: "Job scheduling and resource management inefficiencies that strand allocation-level capacity",
    concepts: [
      {
        id: "queue-starvation",
        itemCode: "WKL-01",
        layerCode: "WKL",
        slug: "queue-starvation",
        name: "Queue Starvation",
        shortDescription:
          "Jobs waiting indefinitely in scheduling queues due to priority inversion or resource hoarding by long-running workloads.",
        definition:
          "Queue starvation occurs when higher-priority or resource-intensive jobs perpetually block lower-priority workloads from acquiring compute resources. Unlike simple resource contention, starvation is characterized by indefinite wait times where jobs never receive allocation despite available headroom, leading to systematic underutilization.",
        characteristics: [
          "Queue wait time exceeding 10× the estimated runtime",
          "Priority inversion where low-priority jobs block medium-priority work",
          "Backlogged short-job queue despite available idle nodes",
          "Job walltime abandonment rates above 15% due to queue fatigue",
        ],
        operationalImpact:
          "20–35% of submitted jobs miss their SLA-defined completion windows due to queue contention. Resulting resource underutilization ranges 15–25% of total cluster capacity. For a $10M cluster, this represents $1.5–2.5M in stranded investment annually.",
        commonCauses: [
          "FCFS scheduling without backfill",
          "Overly conservative resource requests (4× actual utilization)",
          "No preemption for batch workloads",
          "Insufficient queue partitioning for workload classes",
        ],
        exampleScenario:
          "A research cluster using FCFS has 16 nodes reserved by four long jobs that each requested 4 nodes but use only 2 nodes' worth. The remaining 8 node-equivalents sit idle while 23 short jobs remain queued. Introducing backfill allows short jobs to use those idle resources, increasing throughput 40% without hardware.",
        relatedConceptIds: ["scheduler-drift", "resource-allocation"],
      },
      {
        id: "scheduler-drift",
        itemCode: "WKL-02",
        layerCode: "WKL",
        slug: "scheduler-drift",
        name: "Scheduler Drift",
        shortDescription:
          "Progressive deviation between scheduler-allocated resources and actual workload utilization over time.",
        definition:
          "Scheduler drift is the phenomenon where scheduler resource model diverges from actual workload consumption, leading to increasingly suboptimal placement decisions. This drift typically results from static scheduling policies that fail to account for evolving workload characteristics, hardware heterogeneity, or utilization feedback.",
        characteristics: [
          "Allocation-versus-utilization gap widening beyond 30%",
          "Stale node health data causing misplaced jobs",
          "Scoring model degradation over scheduling cycles",
          "Resource fragmentation increasing as drift compounds",
        ],
        operationalImpact:
          "Cluster utilization drops 15–20% as the scheduler places based on outdated models. The drift compounds each cycle. For a 1,000-core cluster, scheduler drift effectively strands 150–200 cores recoverable through recalibration.",
        commonCauses: [
          "Infrequent scheduler recalibration (quarterly or less)",
          "Static tags that don't reflect dynamic node conditions",
          "Hardware heterogeneity not reflected in weightings",
          "Lack of automated feedback loops",
        ],
        exampleScenario:
          "A cluster optimized for MPI CPU workloads shifts to GPU ML with different memory and network requirements. The scheduler keeps prioritizing CPU cores over memory locality, misplacing GPU jobs and causing 25% longer runtimes. Recalibrating the scheduler weightings recovers 18% of effective capacity.",
        relatedConceptIds: ["queue-starvation", "resource-allocation"],
      },
      {
        id: "resource-allocation",
        itemCode: "WKL-03",
        layerCode: "WKL",
        slug: "resource-allocation",
        name: "Resource Allocation",
        shortDescription:
          "Suboptimal distribution of compute, memory, and I/O resources across competing workloads causing performance degradation.",
        definition:
          "Resource allocation inefficiency manifests when workloads receive disproportionate resource shares relative to their priority or criticality. Unlike queue starvation (preventing start), allocation inefficiency affects running jobs through oversubscription penalties and non-optimal placement.",
        characteristics: [
          "CPU oversubscription exceeding 5:1 causing throttling",
          "Memory ballooning without limits triggering swap thrash",
          "NUMA crossing exceeding 20% performance loss",
          "Cache contention on shared LLC reducing per-core throughput",
        ],
        operationalImpact:
          "Mixed workloads suffer 30–50% degradation from contention. This effectively strands half the compute investment for affected workloads. In multi-tenant settings, noisy-neighbor can collapse one tenant's performance to 20% of baseline.",
        commonCauses: [
          "Lack of quotas or limits for workload classes",
          "Absence of QoS tiers for mixed-criticality workloads",
          "Inadequate cgroup or container resource pinning",
          "Uncontrolled hypervisor or OS scheduling",
        ],
        exampleScenario:
          "On K8s, a batch job spawning 200 pods without QoS consumes all CPU, starving inference pods and lifting p99 latency from 15ms to 950ms. Implementing Guaranteed QoS restores inference SLAs while allowing batch to consume idle cycles.",
        relatedConceptIds: ["idle-gpu-pool", "scheduler-drift"],
      },
      {
        id: "cluster-fragmentation",
        itemCode: "WKL-04",
        layerCode: "WKL",
        slug: "cluster-fragmentation",
        name: "Cluster Fragmentation",
        shortDescription:
          "Fragmentation of the compute pool into small but functionally unusable fragments that cannot host large class-size workloads.",
        definition:
          "Cluster fragmentation describes the state where available compute is scattered into many small free fragments that individually cannot satisfy large job shapes. Even though aggregate capacity looks healthy, a 1,024-GPU job cannot fit if no contiguous free window of 1,024 GPUs exists, leaving that entire capacity stranded.",
        characteristics: [
          "Free-fragment count far exceeding free-accelerator count for similar shape",
          "Largest contiguous free window below the job demand floor",
          "Anti-affinity settings blocking intended co-location of large jobs",
          "Bin packing slack distributed across many partially used nodes",
        ],
        operationalImpact:
          "Fragmentation strands 20–40% of a reserved pool depending on workload mix. For a 4,096-accelerator site, that is roughly 1,000 unusable accelerators worth $7–12M in stranded investment, surfaced only during transient spikes in demand.",
        commonCauses: [
          "Lack of size-aware admission control for large jobs",
          "Platform modeling defragmentation at too granular a shape",
          "Small jobs over-placement into windows meant for large jobs",
          "Absence of gang scheduling or aggregate-aware placement",
        ],
        exampleScenario:
          "A 4,096-GPU cluster shows 20% average free capacity, but no free window larger than 512 GPUs at any time. Six 1,024-GPU training jobs sit queued while 900 fragmented slots remain unused. Enabling co-slot aggregation and shape mapping lets three jobs start back-to-back, recovering 30% of the fleet.",
        relatedConceptIds: ["resource-allocation", "oversubscription"],
      },
      {
        id: "oversubscription",
        itemCode: "WKL-05",
        layerCode: "WKL",
        slug: "oversubscription",
        name: "Oversubscription",
        shortDescription:
          "Overcommitting node capacity beyond physical limits that produces burst contention and latency violations.",
        definition:
          "Oversubscription risk occurs when the scheduler or hypervisor allocates more aggregate resources (CPU, memory, or I/O) than a node can physically provide, relying on statistical multiplexing. When workloads burst together, nodes approach full contention and performance degrades well below what any single workload expects.",
        characteristics: [
          "Node admission CPU ratio above 4:1 without QoS protection",
          "Memory requested exceeding physical capacity in corner cases",
          "Scheduled pod count constantly at the hypervisor ceiling",
          "p99 latency spikes during co-scheduled burst peaks",
        ],
        operationalImpact:
          "Oversubscription can spike tenant p99 latency 5–20× during correlated bursts, triggering SLA penalties. Under-utilized, it strands 15–30% of licensed capacity; correctly rationed, it sustains 90%+ utilization instead of the 60–70% seen on under-provisioned fleets.",
        commonCauses: [
          "Aggressive capacity filling without burst or headroom limits",
          "Converged workloads with highly correlated peak alignment",
          "Unenforced admission control and saturation timeouts",
          "Missing tenant isolation budgets for shared resources",
        ],
        exampleScenario:
          "A Kubernetes node with 64GB RAM admits 90 vCPUs of burstable pods. On a Monday batch burst all pods run simultaneously, swap thrashing climbs and p99 latency jumps from 18ms to 520ms. Reverting to per-tenant quotas that allow only 80% of capacity to burst restores the SLA-vs-cost balance without adding capacity.",
        relatedConceptIds: ["resource-allocation", "cluster-fragmentation"],
      },
    ],
  },
]

export function getCategoryByConceptId(
  conceptId: string,
): TaxonomyCategory | undefined {
  return taxonomyData.find((cat) =>
    cat.concepts.some((c) => c.id === conceptId),
  )
}

export function getConceptById(
  conceptId: string,
): TaxonomyConcept | undefined {
  for (const cat of taxonomyData) {
    const concept = cat.concepts.find((c) => c.id === conceptId)
    if (concept) return concept
  }
  return undefined
}

export function getRelatedConcepts(
  conceptIds: string[],
): TaxonomyConcept[] {
  return conceptIds
    .map((id) => getConceptById(id))
    .filter((c): c is TaxonomyConcept => c !== undefined)
}

export function getAllConceptsFlattened(): TaxonomyConcept[] {
  return taxonomyData.flatMap((cat) => cat.concepts)
}

export function getAdjacentConcepts(
  conceptId: string,
): { prev: TaxonomyConcept | null; next: TaxonomyConcept | null } {
  const all = getAllConceptsFlattened()
  const index = all.findIndex((c) => c.id === conceptId)
  return {
    prev: index > 0 ? all[index - 1] : null,
    next: index < all.length - 1 ? all[index + 1] : null,
  }
}